sudo: required
language: minimal
services:
- docker
script:
- pip install awscli --upgrade --user 
- eval $(aws ecr get-login --region us-east-1 --no-include-email) 
- docker build -t 234514569215.dkr.ecr.us-east-1.amazonaws.com/queue-worker:$TRAVIS_BRANCH .

deploy:
  provider: script
  script: docker push 234514569215.dkr.ecr.us-east-1.amazonaws.com/queue-worker:$TRAVIS_BRANCH
  if: tag IS present

env:
  global:
  - secure: jz4+2pWtwC5cYDYEuc/MtWxhL8mGup9Wfw0hon0x9xpAH+qPt+MhX3QYal8u4rXjCv9yaFr7S16VJ5vH5X+VTpLIaqqqAYZDmjRBg+QAX60kB1r36uqi8nQpwQMKRWDZC2Rr6Nq2NZ114uzj2kgiNjZoFty5b1ArMBJXqcGkf1TuEl2MfN+55hyAjSMwK6DPWDNAcb8QuqySenIjKCi3AxLIDwTv9b6sFiZsw1gGeRWCr46aAULgMLw9B18PUuTBLrmuQIR5npZInHDB1XbM/9LKCKUO8i9gFfaHGsG1flpgur+74+wNO8PwGLETTwiKIHQmgn0vqKPGOWGtpftPTKYL1VQauTNfzB526Les2BAf/gVc6Sbnli7WRi8Ac2PNZhs6AcF7FmFCDlwug0Q010AKY+15lZectWcrijAmQCLB7ctJvD/2QZ7DOHTmuMRPHGzUdwXsfj/HzTK2HJl9ykdC7/ccz+QnNfmEF4oIcqCBXhlpwOezxhXXXCIfj2vxPymQ/9hhKFMftqA9q68qI1l1pKo5mr+rraZThIJn7Ssq9WWiPvEDmD9yWfNo7H9CoVcqGiHJkt/e/4eopuwHNyWTJGa2YrB4Z1/tvK7iwQC4kSXNQHgAj7SvXy56NbeNbZwxuhL0vVEVPpVFDUD5pXx+HXx2RMvuyH/Am3Q7r44=
  - secure: JbXTMNjxc74yqJInP7ufAwm8Cr1sAhUxGpFf8rEJ/EPaAzJ01XmVMX7DHJKVw7DgMKaloC9e0vnMaALNE9NEULHDtiD9kfBHkxyAxoN0DTKtZiFrNByhWich1skmdIaGkvL8ki4IaXIMk1IbAnwhl27ZeGaX2jb1IBI8U5lQYVvVCf+HJpSM7xRCTj9k8/glqEA9qVzqPQ4eHKglDIDsCK3FzdWqWqqhCG+CKr6g5BWz6N41KP4dGd74UvlUigqpVMQ7s9JE1Strscu9luzhSRFpcvDdIdb/QRaBW8rqwn0U+SDCNpyWrsiyBuK1Ij2gLc7OmtxSeDPVHTeemglc22SN2k8sv5iEQU+Ck+eETPDcga+Iu2aZgIr8ET36aq2rdwOuokfDb+2zwq7bW6jQmK5mD9CemsOmKW8ka8XOoNNpBkpYTp/SO1O4F7dFcb+6GPb7acNoMm5eIeGSx46VwNUDQIJkm6/AQ7MNQnWjRXO0ZG+tGlhQceIOFu/wM3lra/ICzNSXEmUoedEd4q1Btp+JAlK04isOHPvtTCr6SzGnEHZZNnleU6/HDV88ArsTM3JHtWXfPnu8JgW81i7CShCgO3TUafMAHzocyvbeCeei03svEBpCTOhHHRdQ/y8Q0/ZwEufAis0bZtTx+r602kp2PznK8RqxZ+BGgQ6hs4w=
